import 'dart:io';

const String _beginMarker =
    '    # BEGIN REGION PACK ASSETS - generated by tool/generate_region_pack_assets.dart';
const String _endMarker = '    # END REGION PACK ASSETS';

Future<void> main() async {
  final projectRoot = Directory.current;
  final regionPacksRoot = Directory(
    '${projectRoot.path}${Platform.pathSeparator}assets${Platform.pathSeparator}region_packs',
  );
  final pubspecFile = File(
    '${projectRoot.path}${Platform.pathSeparator}pubspec.yaml',
  );

  if (!regionPacksRoot.existsSync()) {
    stderr.writeln('Missing assets/region_packs directory.');
    exitCode = 1;
    return;
  }
  if (!pubspecFile.existsSync()) {
    stderr.writeln('Missing pubspec.yaml.');
    exitCode = 1;
    return;
  }

  final assetPaths = await regionPacksRoot
      .list(recursive: true, followLinks: false)
      .where((entity) => entity is File)
      .cast<File>()
      .map((file) => _relativeAssetPath(projectRoot, file))
      .where(_isRuntimeRegionPackAsset)
      .toList();
  assetPaths.sort();

  final pubspec = await pubspecFile.readAsString();
  final beginIndex = pubspec.indexOf(_beginMarker);
  final endIndex = pubspec.indexOf(_endMarker);
  if (beginIndex == -1 || endIndex == -1 || endIndex < beginIndex) {
    stderr.writeln('Could not find generated asset markers in pubspec.yaml.');
    exitCode = 1;
    return;
  }

  final generatedBlock = [
    _beginMarker,
    for (final assetPath in assetPaths) '    - $assetPath',
    _endMarker,
  ].join('\n');
  final updatedPubspec =
      pubspec.substring(0, beginIndex) +
      generatedBlock +
      pubspec.substring(endIndex + _endMarker.length);

  await pubspecFile.writeAsString(updatedPubspec);
  stdout.writeln('Wrote ${assetPaths.length} region-pack asset entries.');
}

String _relativeAssetPath(Directory projectRoot, File file) {
  final rootPath = projectRoot.absolute.path;
  final filePath = file.absolute.path;
  final relativePath = filePath.startsWith(rootPath)
      ? filePath.substring(rootPath.length + 1)
      : filePath;
  return relativePath.replaceAll('\\', '/');
}

bool _isRuntimeRegionPackAsset(String assetPath) {
  return assetPath.endsWith('/manifest.json') ||
      assetPath.endsWith('/metadata.json') ||
      assetPath.endsWith('.geojson');
}
