import 'dart:io';

const String _beginMarker =
    '    # BEGIN REGION PACK ASSETS - generated by tool/generate_region_pack_assets.dart';
const String _endMarker = '    # END REGION PACK ASSETS';
const String _bundleModeEnvVar = 'EXPLORED_BUNDLED_REGION_PACKS';
const String _bundleModeAll = 'all';
const String _bundleModeSeed = 'seed';
const List<String> _packRoots = <String>[
  'assets/region_packs',
  'assets/entity_packs',
];
const Set<String> _seedBundledRegionPackCountrySlugs = <String>{
  'andorra',
  'austria',
  'belgium',
};

Future<void> main() async {
  final projectRoot = Directory.current;
  final pubspecFile = File(
    '${projectRoot.path}${Platform.pathSeparator}pubspec.yaml',
  );

  if (!pubspecFile.existsSync()) {
    stderr.writeln('Missing pubspec.yaml.');
    exitCode = 1;
    return;
  }
  final bundleMode = Platform.environment[_bundleModeEnvVar]?.toLowerCase();
  final bundleAllRegionPacks = bundleMode != _bundleModeSeed;

  final assetPaths = <String>[];
  for (final root in _packRoots) {
    final packRoot = Directory(
      '${projectRoot.path}${Platform.pathSeparator}${root.replaceAll('/', Platform.pathSeparator)}',
    );
    if (!packRoot.existsSync()) {
      continue;
    }
    final rootAssetPaths = await packRoot
        .list(recursive: true, followLinks: false)
        .where((entity) => entity is File)
        .cast<File>()
        .map((file) => _relativeAssetPath(projectRoot, file))
        .where(
          (assetPath) => _isBundledRuntimeRegionPackAsset(
            assetPath,
            bundleAllRegionPacks: bundleAllRegionPacks,
          ),
        )
        .toList();
    assetPaths.addAll(rootAssetPaths);
  }
  assetPaths.sort();

  final pubspec = await pubspecFile.readAsString();
  final beginIndex = pubspec.indexOf(_beginMarker);
  final endIndex = pubspec.indexOf(_endMarker);
  if (beginIndex == -1 || endIndex == -1 || endIndex < beginIndex) {
    stderr.writeln('Could not find generated asset markers in pubspec.yaml.');
    exitCode = 1;
    return;
  }

  final generatedBlock = [
    _beginMarker,
    for (final assetPath in assetPaths) '    - $assetPath',
    _endMarker,
  ].join('\n');
  final updatedPubspec =
      pubspec.substring(0, beginIndex) +
      generatedBlock +
      pubspec.substring(endIndex + _endMarker.length);

  await pubspecFile.writeAsString(updatedPubspec);
  final resolvedBundleMode = bundleAllRegionPacks
      ? _bundleModeAll
      : _bundleModeSeed;
  stdout.writeln(
    'Wrote ${assetPaths.length} bundled pack asset entries using '
    '$resolvedBundleMode mode.',
  );
}

String _relativeAssetPath(Directory projectRoot, File file) {
  final rootPath = projectRoot.absolute.path;
  final filePath = file.absolute.path;
  final relativePath = filePath.startsWith(rootPath)
      ? filePath.substring(rootPath.length + 1)
      : filePath;
  return relativePath.replaceAll('\\', '/');
}

bool _isRuntimeRegionPackAsset(String assetPath) {
  if (assetPath.split('/').any((segment) => segment.startsWith('.'))) {
    return false;
  }
  return assetPath.endsWith('.ndjson') ||
      assetPath.endsWith('.geojson') ||
      assetPath.endsWith('.json');
}

bool _isBundledRuntimeRegionPackAsset(
  String assetPath, {
  required bool bundleAllRegionPacks,
}) {
  if (!_isRuntimeRegionPackAsset(assetPath)) {
    return false;
  }
  if (!assetPath.startsWith('assets/region_packs/')) {
    return true;
  }
  if (bundleAllRegionPacks) {
    return true;
  }
  final countrySlug = _extractRegionPackCountrySlug(assetPath);
  return countrySlug != null &&
      _seedBundledRegionPackCountrySlugs.contains(countrySlug);
}

String? _extractRegionPackCountrySlug(String assetPath) {
  final parts = assetPath.split('/');
  if (parts.length < 4 || parts[0] != 'assets' || parts[1] != 'region_packs') {
    return null;
  }
  switch (parts[2]) {
    case 'objects':
    case 'regions':
    case 'stats':
      return parts[3];
  }
  return null;
}
